version: '{build}'
build: off
deploy: off
#cache:
#  - node_modules
#  - '%APPDATA%\npm-cache'
branches:
  only:
    - master
  except:
    - gh-pages
matrix:
  fast_finish: true
environment:
  matrix:
    - nodejs_version: 4.2
    - nodejs_version: 4.1
    - nodejs_version: 4.0
    - nodejs_version: 0.12
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm dedupe
  - npm prune
test_script:
  - node --version
  - npm --version
  - cmd: npm test
